include("${CMAKE_CURRENT_LIST_DIR}/@PROJECT_NAME@-targets.cmake")

get_target_property(@PROJECT_NAME@_INCLUDE_DIRS @PROJECT_NAME@::@PROJECT_NAME@ INTERFACE_INCLUDE_DIRECTORIES)
set(@PROJECT_NAME@_LIBRARIES @PROJECT_NAME@::@PROJECT_NAME@)
